#############################################################################
# Makefile for building: mainode
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Wed Mar  6 16:21:14 2013
# Project:  mainode.pro
# Template: app
# Command: $(QMAKE) -o Makefile mainode.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fno-strict-aliasing  -DQT_NO_DEBUG -DQT_SHARED -DQT_TABLET_SUPPORT -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fno-strict-aliasing  -DQT_NO_DEBUG -DQT_SHARED -DQT_TABLET_SUPPORT -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/lib64/qt-3.3/mkspecs/default -I. -I. -Isrc -I$(QTDIR)/include
LINK     = g++
LFLAGS   = 
#LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -lqt-mt -lXext -lX11 -lm
LIBS     = $(SUBLIBS) -lcv -lcvaux -lcxcore -lhighgui -lboost_thread -lboost_system -lboost_timer -lboost_log -lboost_program_options
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = src/bit_feature.h \
		src/bits.hpp \
		src/comm_arg.hpp \
		src/comm_box.hpp \
		src/comm_para.hpp \
		src/comm_window.hpp \
		src/command.hpp \
		src/command_recv_service.hpp \
		src/connection_build_service.hpp \
		src/dcsp_fifo.h \
		src/fdutils.h \
		src/integral.h \
		src/ipoint.h \
		src/lib_load_service.hpp \
		src/log.h \
		src/match_analyser.hpp \
		src/match_stream.hpp \
		src/match_utils.h \
		src/matcher_manager.hpp \
		src/newlib.h \
		src/packet.hpp \
		src/packet_handle_center.hpp \
		src/raw.hpp \
		src/server.hpp \
		src/utils.h
SOURCES = src/bit_feature.cpp \
		src/comm_arg.cpp \
		src/comm_box.cpp \
		src/command.cpp \
		src/command_recv_service.cpp \
		src/connection_build_service.cpp \
		src/integral.cpp \
		src/ipoint.cpp \
		src/lib_load_service.cpp \
		src/log.cpp \
		src/main.cpp \
		src/match_analyser.cpp \
		src/match_stream.cpp \
		src/match_utils.cpp \
		src/matcher_manager.cpp \
		src/newlib.cpp \
		src/packet_handle_center.cpp \
		src/raw.cpp \
		src/server.cpp \
		src/utils.cpp
OBJECTS = bit_feature.o \
		comm_arg.o \
		comm_box.o \
		command.o \
		command_recv_service.o \
		connection_build_service.o \
		integral.o \
		ipoint.o \
		lib_load_service.o \
		log.o \
		main.o \
		match_analyser.o \
		match_stream.o \
		match_utils.o \
		matcher_manager.o \
		newlib.o \
		packet_handle_center.o \
		raw.o \
		server.o \
		dcsp_fifo.o \
		utils.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = 
OBJMOC = 
DIST	   = mainode.pro
QMAKE_TARGET = mainode
DESTDIR  = 
TARGET   = mainode

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: mainode.pro  /usr/lib64/qt-3.3/mkspecs/default/qmake.conf /usr/lib64/qt-3.3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile mainode.pro
qmake: 
	@$(QMAKE) -o Makefile mainode.pro

dist: 
	@mkdir -p .tmp/mainode && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/mainode/ && ( cd `dirname .tmp/mainode` && $(TAR) mainode.tar mainode && $(GZIP) mainode.tar ) && $(MOVE) `dirname .tmp/mainode`/mainode.tar.gz . && $(DEL_FILE) -r .tmp/mainode

mocclean:

uiclean:

yaccclean:
lexclean:
clean:
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

bit_feature.o: src/bit_feature.cpp src/bit_feature.h \
		src/integral.h \
		src/log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bit_feature.o src/bit_feature.cpp

comm_arg.o: src/comm_arg.cpp src/utils.h \
		src/comm_arg.hpp \
		src/comm_para.hpp \
		src/log.h \
		src/fdutils.h \
		src/ipoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o comm_arg.o src/comm_arg.cpp

comm_box.o: src/comm_box.cpp src/comm_box.hpp \
		src/server.hpp \
		src/comm_para.hpp \
		src/packet.hpp \
		src/utils.h \
		src/command.hpp \
		src/raw.hpp \
		src/log.h \
		src/fdutils.h \
		src/ipoint.h \
		src/matcher_manager.hpp \
		src/comm_arg.hpp \
		src/comm_window.hpp \
		src/match_analyser.hpp \
		src/match_utils.h \
		src/integral.h \
		src/newlib.h \
		src/bit_feature.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o comm_box.o src/comm_box.cpp

command.o: src/command.cpp src/command.hpp \
		src/server.hpp \
		src/dcsp_fifo.h \
		src/matcher_manager.hpp \
		src/log.h \
		src/utils.h \
		src/comm_arg.hpp \
		src/comm_para.hpp \
		src/fdutils.h \
		src/ipoint.h \
		src/packet.hpp \
		src/comm_box.hpp \
		src/comm_window.hpp \
		src/match_analyser.hpp \
		src/raw.hpp \
		src/match_utils.h \
		src/integral.h \
		src/newlib.h \
		src/bit_feature.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o command.o src/command.cpp

command_recv_service.o: src/command_recv_service.cpp src/command_recv_service.hpp \
		src/server.hpp \
		src/matcher_manager.hpp \
		src/packet.hpp \
		src/command.hpp \
		src/dcsp_fifo.h \
		src/log.h \
		src/utils.h \
		src/comm_arg.hpp \
		src/comm_para.hpp \
		src/fdutils.h \
		src/ipoint.h \
		src/raw.hpp \
		src/comm_box.hpp \
		src/comm_window.hpp \
		src/match_analyser.hpp \
		src/match_utils.h \
		src/integral.h \
		src/newlib.h \
		src/bit_feature.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o command_recv_service.o src/command_recv_service.cpp

connection_build_service.o: src/connection_build_service.cpp src/connection_build_service.hpp \
		src/match_stream.hpp \
		src/server.hpp \
		src/matcher_manager.hpp \
		src/packet.hpp \
		src/log.h \
		src/utils.h \
		src/comm_arg.hpp \
		src/comm_para.hpp \
		src/fdutils.h \
		src/ipoint.h \
		src/raw.hpp \
		src/lib_load_service.hpp \
		src/newlib.h \
		src/bit_feature.h \
		src/integral.h \
		src/comm_box.hpp \
		src/comm_window.hpp \
		src/match_analyser.hpp \
		src/command.hpp \
		src/match_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connection_build_service.o src/connection_build_service.cpp

integral.o: src/integral.cpp src/integral.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integral.o src/integral.cpp

ipoint.o: src/ipoint.cpp src/utils.h \
		src/ipoint.h \
		src/comm_para.hpp \
		src/log.h \
		src/fdutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ipoint.o src/ipoint.cpp

lib_load_service.o: src/lib_load_service.cpp src/lib_load_service.hpp \
		src/match_stream.hpp \
		src/server.hpp \
		src/matcher_manager.hpp \
		src/packet.hpp \
		src/newlib.h \
		src/log.h \
		src/utils.h \
		src/comm_arg.hpp \
		src/comm_para.hpp \
		src/fdutils.h \
		src/ipoint.h \
		src/raw.hpp \
		src/bit_feature.h \
		src/integral.h \
		src/comm_box.hpp \
		src/comm_window.hpp \
		src/match_analyser.hpp \
		src/command.hpp \
		src/match_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lib_load_service.o src/lib_load_service.cpp

log.o: src/log.cpp src/log.h \
		src/fdutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o log.o src/log.cpp

main.o: src/main.cpp src/server.hpp \
		src/comm_arg.hpp \
		src/packet.hpp \
		src/log.h \
		src/comm_box.hpp \
		src/comm_window.hpp \
		src/match_analyser.hpp \
		src/matcher_manager.hpp \
		src/raw.hpp \
		src/comm_para.hpp \
		src/utils.h \
		src/command.hpp \
		src/fdutils.h \
		src/ipoint.h \
		src/match_utils.h \
		src/integral.h \
		src/newlib.h \
		src/bit_feature.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

match_analyser.o: src/match_analyser.cpp src/match_analyser.hpp \
		src/bits.hpp \
		src/server.hpp \
		src/match_stream.hpp \
		src/match_utils.h \
		src/packet.hpp \
		src/matcher_manager.hpp \
		src/fdutils.h \
		src/integral.h \
		src/newlib.h \
		src/bit_feature.h \
		src/log.h \
		src/raw.hpp \
		src/utils.h \
		src/comm_arg.hpp \
		src/comm_para.hpp \
		src/ipoint.h \
		src/comm_box.hpp \
		src/comm_window.hpp \
		src/command.hpp \
		src/lib_load_service.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o match_analyser.o src/match_analyser.cpp

match_stream.o: src/match_stream.cpp src/match_stream.hpp \
		src/packet.hpp \
		src/utils.h \
		src/match_utils.h \
		src/server.hpp \
		src/bits.hpp \
		src/comm_box.hpp \
		src/comm_window.hpp \
		src/matcher_manager.hpp \
		src/lib_load_service.hpp \
		src/raw.hpp \
		src/log.h \
		src/comm_arg.hpp \
		src/comm_para.hpp \
		src/fdutils.h \
		src/ipoint.h \
		src/newlib.h \
		src/bit_feature.h \
		src/integral.h \
		src/match_analyser.hpp \
		src/command.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o match_stream.o src/match_stream.cpp

match_utils.o: src/match_utils.cpp src/match_utils.h \
		src/log.h \
		src/fdutils.h \
		src/integral.h \
		src/newlib.h \
		src/bit_feature.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o match_utils.o src/match_utils.cpp

matcher_manager.o: src/matcher_manager.cpp src/matcher_manager.hpp \
		src/connection_build_service.hpp \
		src/lib_load_service.hpp \
		src/server.hpp \
		src/log.h \
		src/utils.h \
		src/comm_arg.hpp \
		src/comm_para.hpp \
		src/fdutils.h \
		src/ipoint.h \
		src/packet.hpp \
		src/raw.hpp \
		src/newlib.h \
		src/bit_feature.h \
		src/integral.h \
		src/comm_box.hpp \
		src/comm_window.hpp \
		src/match_analyser.hpp \
		src/command.hpp \
		src/match_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o matcher_manager.o src/matcher_manager.cpp

newlib.o: src/newlib.cpp src/newlib.h \
		src/log.h \
		src/bit_feature.h \
		src/integral.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newlib.o src/newlib.cpp

packet_handle_center.o: src/packet_handle_center.cpp src/packet_handle_center.hpp \
		src/server.hpp \
		src/connection_build_service.hpp \
		src/match_stream.hpp \
		src/packet.hpp \
		src/raw.hpp \
		src/log.h \
		src/comm_arg.hpp \
		src/comm_box.hpp \
		src/comm_window.hpp \
		src/match_analyser.hpp \
		src/matcher_manager.hpp \
		src/comm_para.hpp \
		src/utils.h \
		src/command.hpp \
		src/fdutils.h \
		src/ipoint.h \
		src/match_utils.h \
		src/integral.h \
		src/newlib.h \
		src/bit_feature.h \
		src/lib_load_service.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o packet_handle_center.o src/packet_handle_center.cpp

raw.o: src/raw.cpp src/raw.hpp \
		src/log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o raw.o src/raw.cpp

server.o: src/server.cpp src/server.hpp \
		src/comm_arg.hpp \
		src/comm_para.hpp \
		src/match_utils.h \
		src/match_stream.hpp \
		src/connection_build_service.hpp \
		src/lib_load_service.hpp \
		src/packet_handle_center.hpp \
		src/command_recv_service.hpp \
		src/packet.hpp \
		src/log.h \
		src/comm_box.hpp \
		src/comm_window.hpp \
		src/match_analyser.hpp \
		src/matcher_manager.hpp \
		src/raw.hpp \
		src/utils.h \
		src/command.hpp \
		src/fdutils.h \
		src/ipoint.h \
		src/integral.h \
		src/newlib.h \
		src/bit_feature.h \
		src/dcsp_fifo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o server.o src/server.cpp

utils.o: src/utils.cpp src/utils.h \
		src/comm_para.hpp \
		src/log.h \
		src/fdutils.h \
		src/ipoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o src/utils.cpp

####### Install

install:  

uninstall:  

